openapi: 3.0.1
info:
  title: Polygon Stocks API
  description: Access various financial data and information from Polygon.io's Stocks API.
  version: "v1"
servers:
  - url: [https://api.polygon.io/v2] # Update the URL to Polygon's API base URL
paths:
  /aggs/ticker/{stocksTicker}/range/{multiplier}/{timespan}/{from}/{to}:
    get:
      operationId: getAggregateBars
      summary: Get aggregate bars for a stock over a given date range in custom time window sizes.
      parameters:
        - in: path
          name: stocksTicker
          schema:
            type: string
          required: true
          description: The case-sensitive ticker symbol (e.g., AAPL).
        - in: path
          name: multiplier
          schema:
            type: integer
          required: true
          description: The size of the timespan multiplier (e.g., 1).
        - in: path
          name: timespan
          schema:
            type: string
          required: true
          description: The size of the time window (e.g., day).
        - in: path
          name: from
          schema:
            type: string
          required: true
          description: The start of the aggregate time window (YYYY-MM-DD).
        - in: path
          name: to
          schema:
            type: string
          required: true
          description: The end of the aggregate time window (YYYY-MM-DD).
        - in: query
          name: adjusted
          schema:
            type: boolean
          description: Whether or not the results are adjusted for splits (true or false).
        - in: query
          name: sort
          schema:
            type: string
          description: Sort the results by timestamp (asc or desc).
        - in: query
          name: limit
          schema:
            type: integer
          description: Limits the number of base aggregates queried (Max 50000).
      responses:
        "200":
          description: OK
  /aggs/grouped/locale/us/market/stocks/{date}:
    get:
      operationId: getGroupedDailyBars
      summary: Get the daily open, high, low, and close (OHLC) for the entire stocks/equities markets.
      parameters:
        - in: path
          name: date
          schema:
            type: string
          required: true
          description: The beginning date for the aggregate window (YYYY-MM-DD).
        - in: query
          name: adjusted
          schema:
            type: boolean
          description: Whether or not the results are adjusted for splits (true or false).
        - in: query
          name: include_otc
          schema:
            type: boolean
          description: Include OTC securities in the response (true or false).
      responses:
        "200":
          description: OK
# Define other paths for additional Polygon API endpoints if needed.
